### ISSUE TITLE
uint80 is more expansive on read(unlock) and cheaper in write(lock) re uint256

### ISSUE THREAD

**Issue by orenyodfat** [daostack/access_control#39]
as unlock operation is seems to be more frequently be used  , I suggest to use uint256 instead of uint80

**Comment by ben-kaufman** [comment]
The ratio between the cost added to write to the cost reduced from read is about 120:1 (60,000 more on write but 500 less on read). Gaswise I'd say it will be better to leave it as 80 bits. However, there is also the consideration of standartization, as `uint256` is basically the standard for most things it might be better to us it instead.

**Comment by leviadam** [comment]
I think @orenyodfat has a point as unlocking is a much more frequent. Plus the standardtization, I think we should start with 256, and see if this makes things too expensive, e.g in Arc.

**Comment by dev-matan-tsuberi** [comment]
@leviadam If you're suggesting running the Arc tests and seeing how much `read` happens vs `write`, that's not necessarily a good estimate of real world usage.

I think I agree with @orenyodfat, If we can't definitely say its better and justify this decision, its not going to pass as an EIP. And I imagine `read` will actually happen more than 120 times `write`.
