### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by tarrencev** [daostack/access_control#43]
The readme suggests installing through NPM but as far as I can tell the package has not been published yet

**Comment by leviadam** [comment]
Hi @tarrencev :)

Thanks for catching that. For some reason the package was private.

Just made it public.

**Comment by tsuberim** [comment]
Hi @tarrencev Just published [@daostack/access_control@0.1.0](https://www.npmjs.com/package/@daostack/access_control), I'll also add this to CI so it stays in sync with the repo.
